version: "3.8"

services:
  db:
    container_name: management_system
    image: postgres:14.17
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_pooling:/var/lib/postgresql/data

volumes:
  pg_pooling: